local dial_map = require("dial.map")

vim.keymap.set("n", "<C-i>", function()
    dial_map.manipulate("increment", "normal")
end)
vim.keymap.set("n", "<C-x>", function()
    dial_map.manipulate("decrement", "normal")
end)
vim.keymap.set("n", "g<C-i>", function()
    dial_map.manipulate("increment", "gnormal")
end)
vim.keymap.set("n", "g<C-x>", function()
    dial_map.manipulate("decrement", "gnormal")
end)
vim.keymap.set("x", "<C-i>", function()
    dial_map.manipulate("increment", "visual")
end)
vim.keymap.set("x", "<C-x>", function()
    dial_map.manipulate("decrement", "visual")
end)
vim.keymap.set("x", "g<C-i>", function()
    dial_map.manipulate("increment", "gvisual")
end)
vim.keymap.set("x", "g<C-x>", function()
    dial_map.manipulate("decrement", "gvisual")
end)
