env:
  TERM: xterm-256color

window:
  opacity: 0.97
  padding:
    x: 10
    y: 10
  decorations: buttonless
  startup_mode: Maximized

scrolling:
  history: 0
  multiplier: 0

colors:
  primary:
    background: "0x273136"
    foreground: "0xe1e2e3"

  normal:
    black: "0x1c1e1f"
    red: "0xf76c7c"
    green: "0x9cd57b"
    yellow: "0xe3d367"
    blue: "0x78cee9"
    magenta: "0xbaa0f8"
    cyan: "0xf3a96a"
    white: "0xe1e2e3"

  bright:
    black: "0x82878b"
    red: "0xf76c7c"
    green: "0x9cd57b"
    yellow: "0xe3d367"
    blue: "0x78cee9"
    magenta: "0xbaa0f8"
    cyan: "0xf3a96a"
    white: "0xe1e2e3"

draw_bold_text_with_bright_colors: true

font:
  size: 16
  normal:
    # family: SFMono Nerd Font
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    # family: SFMono Nerd Font
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    # family: SFMono Nerd Font
    family: JetBrainsMono Nerd Font
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

key_bindings:
  - { key: Return, mods: Command, action: ToggleFullscreen }
  - { key: F, mods: Command|Control, action: None }
