env:
  TERM: xterm-256color

window:
  padding:
    x: 10
    y: 10
  scrolling: 0
  decorations: none

alt_send_esc: false

cursor:
  style:
    shape: Beam

scrolling:
  history: 0
  multiplier: 0

# Colors (Gruvbox dark)
colors:
  primary:
    background: "0x273136"
    foreground: "0xe1e2e3"

  normal:
    black: "0x1c1e1f"
    red: "0xf76c7c"
    green: "0x9cd57b"
    yellow: "0xe3d367"
    blue: "0x78cee9"
    magenta: "0xbaa0f8"
    cyan: "0xf3a96a"
    white: "0xe1e2e3"

  bright:
    black: "0x1c1e1f"
    red: "0xf76c7c"
    green: "0x9cd57b"
    yellow: "0xe3d367"
    blue: "0x78cee9"
    magenta: "0xbaa0f8"
    cyan: "0xf3a96a"
    white: "0xe1e2e3"

font:
  normal:
    family: SFMono Nerd Font
    style: Regular
  size: 14
  use_thin_strokes: true
  offset:
    x: 1
    y: 1

key_bindings:
  - { key: Return, mods: Command, action: ToggleFullscreen }
  - { key: F, mods: Command|Control, action: None }
