#!/bin/bash

namespace="${1}"
pod="${2}"
containers=$(kubectl get "${pod}" -n "${namespace}" -o jsonpath='{range .spec.containers[*]}{.name}{"\n"}{end}')

if [[ $(echo "$containers" | wc -l) -gt 1 ]]; then
    container=$(echo "${containers}" | fzf)
    kubectl exec -it "${pod}" -n "${namespace}" -c "${container}" -- sh
else
    kubectl exec -it "${pod}" -n "${namespace}" -- sh
fi
