#!/bin/sh

pid=$(echo "$1" | awk '{print $2}' | paste -s -d, -)

if [ "x$pid" = "x" ]; then
    exit 1
fi

INFO=$(ps -o pid,vsz=MEMORY -o user,group=GROUP -o comm,args=ARGS -p $pid)
INFO+="\n\n"
INFO+=$(lsof -w -p $pid)

echo -e "$INFO"
