# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = gsettings set org.gnome.desktop.interface gtk-theme Nordic
exec-once = gsettings set org.gnome.desktop.interface gtk-application-prefer-dark-theme true
exec-once = gsettings set org.gnome.desktop.interface icon-theme Papirus-Dark

exec-once = waybar
exec-once = hyprpaper
exec-once = nm-applet --indicator
exec-once = systemctl --user start plasma-polkit-agent
exec-once = swaync
exec-once = [workspace 1 silent] firefox
exec-once = [workspace 2 silent] $terminal
