preload = $HOME/.dotfiles/assets/wallpapers/hzmg6dgeja4d1.jpeg
wallpaper = , $HOME/.dotfiles/assets/wallpapers/hzmg6dgeja4d1.jpeg

# preload = /home/magnus/.dotfiles/assets/wallpapers/lmda9tam554d1.jpeg
# wallpaper = , /home/magnus/.dotfiles/assets/wallpapers/lmda9tam554d1.jpeg

# preload = /home/magnus/.dotfiles/assets/wallpapers/rojaobteb54d1.jpeg
# wallpaper = , /home/magnus/.dotfiles/assets/wallpapers/rojaobteb54d1.jpeg
