# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = tile-brave-devtools
    match:class = Brave-browser
    match:title = DevTools.*
}

windowrule {
    name = tile-wine-virtual-desktop
    match:class = Wine
    match:title = virtual - Wine desktop
}

windowrule {
    name = float-1password-quickaccess
    match:class = 1Password
    match:title = Quick Access — 1Password
    float = true
    center = true
    no_blur = true
    stay_focused = true
    allows_input = true
}

windowrule {
    name = rofi-stay-focused
    match:class = Rofi
    stay_focused = true
}

windowrule {
    name = ueberzugpp
    match:class = ueberzugpp.*
    float = true
    no_blur = true
    no_anim = true
    no_shadow = true
    border_size = 0
    pin = true
    no_focus = true
}
