# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = tile, class:Brave-browser, title:(DevTools.*)
windowrulev2 = tile, class:Wine, title:(virtual - Wine desktop)
# windowrulev2 = float, ^(VirtualBox)$
# windowrulev2 = float, ^(VirtualBox Machine)$

windowrulev2 = float,class:^(thunderbird)$
windowrulev2 = tile,class:^(thunderbird)$,initialTitle:^Mozilla Thunderbird$

# windowrulev2 = float, class:1password, title:(Quick Access.*)
# windowrulev2 = size 70% 70%, class:1password, title:(Quick Access.*)
# windowrulev2 = center, class:1password, title:(Quick Access.*)
