local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')

Plug('ConradIrwin/vim-bracketed-paste')
Plug('junegunn/vim-easy-align')
Plug('jwalton512/vim-blade')
Plug('mattn/emmet-vim')
Plug('tpope/vim-commentary')
Plug('tpope/vim-fugitive')
Plug('tpope/vim-repeat')
Plug('tpope/vim-surround')
Plug('tpope/vim-abolish')
Plug('wellle/targets.vim')
Plug('editorconfig/editorconfig-vim')
Plug('jremmen/vim-ripgrep')
Plug('junegunn/fzf', { ['do'] = function()
    vim.fn['fzf#install']()
end })
Plug('junegunn/fzf.vim')
Plug('coreyja/fzf.devicon.vim')
Plug('sainnhe/sonokai')
Plug('vim-scripts/edifact.vim')
Plug('Fymyte/rasi.vim')
Plug('windwp/nvim-autopairs')
Plug('windwp/nvim-ts-autotag')
Plug('lukas-reineke/indent-blankline.nvim')
Plug('neovim/nvim-lspconfig')
Plug('onsails/lspkind.nvim')
Plug('nvim-treesitter/nvim-treesitter', { ['do'] = function()
    vim.call('TSUpdate')
end })
Plug('kyazdani42/nvim-web-devicons')
Plug('kyazdani42/nvim-tree.lua')
Plug('nvim-lualine/lualine.nvim')
Plug('akinsho/bufferline.nvim', { ['tag'] = 'v4.*' })
Plug('github/copilot.vim')
Plug('nvim-lua/plenary.nvim')
Plug('CopilotC-Nvim/CopilotChat.nvim', { ['branch'] = 'canary' })
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('saadparwaiz1/cmp_luasnip')
Plug('L3MON4D3/LuaSnip', {['tag'] = 'v1.*', ['do'] = function()
    vim.call('make install_jsregexp')
end })

vim.call('plug#end')

-- Color schemes should be loaded after plug#end().
-- We prepend it with 'silent!' to ignore errors when it's not yet installed.
vim.cmd('silent! colorscheme sonokai')
