#!/usr/bin/env bash

suspend='  Suspend'
lock='  Lock'
log_out='  Log out'
reboot='  Reboot'
power_off='  Power off'

if [ $ROFI_RETV -eq 1 ]
then
    case "$@" in
        "$suspend")
            systemctl suspend
            exit 0
            ;;

        "$lock")
            loginctl lock-session
            exit 0
            ;;

        "$log_out")
            [[ -n $HYPRLAND_INSTANCE_SIGNATURE ]] && hyprctl dispatch exit || swaymsg exit
            exit 0
            ;;

        "$reboot")
            systemctl reboot
            exit 0
            ;;

        "$power_off")
            systemctl poweroff
            exit 0
            ;;

        *) exit 1 ;;
    esac
    exit 0
else
    echo "$suspend"
    echo "$lock"
    echo "$log_out"
    echo "$reboot"
    echo "$power_off"
fi
