[[manager.prepend_keymap]]
on = "<i>"
run = "spot"
desc = "Spot hovered file"

[[manager.prepend_keymap]]
on = "<Tab>"
run = [ "toggle", "arrow 1" ]
desc = "Toggle the current selection state"

[[manager.prepend_keymap]]
on = "<Space>"
run = 'shell -- sushi "$@"'
desc = "Preview hovered file"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[manager.prepend_keymap]]
on   = [ "g", "p" ]
run  = 'cd ~/Pictures'
desc = "Goto ~/Pictures"

[[manager.prepend_keymap]]
on   = "<C-p>"
run  = 'plugin fasd'
desc = "Jump to dir"
