[manager]
prepend_keymap = [
    # Spotting
    { on = "i", run = "spot", desc = "Spot hovered file" },

    # Toggle
    { on = "<Tab>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },

    # Goto
    { on = [ "g", "p" ], run = 'cd ~/Pictures', desc = "Goto ~/Pictures" },

    # Operation
    { on = "l", run  = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "<Enter>", run  = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "<C-p>", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
    { on = "<C-A-p>", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },

    # Tabs
    { on = "<C-h>", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
    { on = "<C-l>", run = "tab_switch 1 --relative",  desc = "Switch to the next tab" },

    { on = "<C-left>", run = "tab_swap -1", desc = "Swap current tab with previous tab" },
    { on = "<C-right>", run = "tab_swap 1",  desc = "Swap current tab with next tab" },

    # Preview 
    { on = "<Space>", run = 'shell -- sushi "$@"', desc = "Preview hovered file" },
    { on = "T", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
    { on = "F", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
]
