[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[manager.prepend_keymap]]
on   = [ "g", "p" ]
run  = 'cd ~/Pictures'
desc = "Goto ~/Pictures"

[[manager.prepend_keymap]]
on   = "<C-p>"
run  = 'plugin fasd'
desc = "Jump to dir"
